version: '3'

services:
  db:
    image: mysql:5.6
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eqdkp
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: sqladmin
    restart: always
    ports:
      - "8080:8080"
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/